splits:
    - prefix: "src/library"
      target: "https://${GH_TOKEN}@github.com/spomky-labs/web-push-lib.git"
    - prefix: "src/bundle"
      target: "https://${GH_TOKEN}@github.com/spomky-labs/web-push-bundle.git"

origins:
    - ^\d+\.\d+\.x$
    - ^\d+\.\d+\.\d+$
